function etaF = b10_integral(x,y,xp,yp,p)
    etaF=p.b4_prefactor/(4) * (2*pi)^3 *...
                    cos(p.theta) *...
                    sqrt(p.Me/p.beta1).* ...
                    besselj(0, 2*pi .* sqrt((x - xp).^2 + (y - yp).^2 )) .* ...
                    exp(-  sqrt(((x - xp).^2 + (y - yp).^2)/(p.Me*p.beta1))) ;
end





